from search import get_metadata
from rich import print
import json
from utils import get_metadata_human, create_hash, read_json
from schema import Schema
import plotext as plt
from transformers import AutoTokenizer
import random
random.seed(42)
tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen2.5-0.5B-Instruct')
def extract(text, model_name, schema_name = None, backend = "openrouter", max_model_len = 8192, max_output_len = 2084, schema = None, version = "3.0", log = True):
    message, metadata, cost, error = get_metadata(
        text, model_name, schema_name=schema_name, backend = backend, max_model_len = max_model_len, max_output_len = max_output_len, schema_json = schema, version = version, log = log
    )
    return metadata

def example1(model_name):
    
    text = """
    Mextract 1.0 are a series of models with sizes: (0.5B, 1.5B, 3B) that can extract metadata from any text. The model has been evaluated on the MOLE
    benchmark and achieved impressive results. The arhitecture is based on Transformer model. The model is released
    under the Apache 2.0 license. The model can process up to 8192 tokens. The model was released in 2025 from KAUST.
    """
    metadata = extract(
        text, model_name, backend = "transformers", schema = schema, version = "3.0",  
    )
    print(metadata)

def example2(model_name, backend="transformers"):
    paper_text = open("static/papers/bbe27eb4/paper_text.txt", "r").read()
    json_schema = json.load(open("src/example_json.json"))
    metadata = extract(
        paper_text, model_name, backend = backend, schema = json_schema, version = "3.0",  
    )
    print(metadata)

def to_remove_keys(gold_metadata):
    keys = [key for key in gold_metadata["annotations_from_paper"] if gold_metadata["annotations_from_paper"][key] == 0]
    print(gold_metadata)
    for key in gold_metadata:
        if key == "annotations_from_paper":
            continue
        if gold_metadata[key] == "" or gold_metadata[key] == [] or gold_metadata[key]== "unknown" or gold_metadata[key]== ["other"]:
            keys.append(key)
    keys += ['Tasks', 'Ethical_Risks', 'Paper_Link', 'Tokenized', 'Test_Split', 'Access', 'Host', 'License', 'Venue_Type', 'Venue_Name', 'Venue_Title', 'Collection_Style', 'Provider', 'Derived_From', 'Volume', 'Unit','Domain'] # difficult to extract
    return keys
def example3(model_name, backend="transformers"):
    link = "https://arxiv.org/pdf/2112.09323"
    hash = create_hash(link)
    schema_name = "jp"
    gold_metadata = get_metadata_human(paper_link=link, schema_name = schema_name)
    schema = Schema(schema_name = schema_name, keys_to_remove = [])
    # print(schema.schema)
    paper_text = open('sample_from_gemini_reversed.txt').read() # reversed is generated by the same way we do synthetic data generation
    paper_text = open(f"static/papers/{hash}/paper_docling.txt", "r").read()
    # paper_text = convert_to_structured(link)

    metadata = extract(
        paper_text, model_name, backend = backend, schema = schema.schema, version = "3.0", log = True 
    )
    print("Raw metadata:", metadata)
    try:
        metadata = read_json(metadata)
    except Exception as e:
        metadata = schema.generate_metadata(method = 'default')
        print(e)
    print("Metadata:", metadata)
    gold_metadata = get_metadata_human(paper_link=link, schema_name = schema_name)
    print("Gold Metadata")
    print(gold_metadata)
    scores = schema.evaluate(metadata, gold_metadata)
    print("Scores:", scores)

def truncate_by_tokens(text, num_tokens = 100):
    return tokenizer.decode(tokenizer.encode(text)[:num_tokens], skip_special_tokens=True)

def remove_keys(schema, style = "keep_all"):
    keys = []
    schema_keys = set(schema.keys())
    if style == "keep_all":
        keys = []
    if style == "remove_options":
        keys = [key for key in schema if "options" in schema[key]]
    if style == "remove_list":
        keys = [key for key in schema if schema[key]["answer_type"] == "List[str]"]
    if style == "keep_string":
        keys = [key for key in schema if schema[key]["answer_type"] != "str"]
    if style == "custom":
        keys = ['Subsets', 'Tasks', 'License', 'Host', 'Domain', 'Collection_Style','Provider', 'Derived_From', 'Script','Venue_Type', 'Access', 'Link', 'HF_Link', 'Ethical_Risks', 'Unit']
    # keys += ["Link", "HF_Link"]
    return keys

def ablate_keys(model_name, backend="transformers", link = "https://arxiv.org/pdf/2112.09323"):
    hash = create_hash(link)
    schema_name = "jp"
    results = []
    schema_json = json.load(open(f"schema/{schema_name}.json"))
    ablations = ['keep_all', 'remove_options', 'remove_list', 'keep_string', 'custom']
    for ablation in ablations:
        keys_to_remove = remove_keys(schema_json, style = ablation)
        schema = Schema(schema_name = schema_name, keys_to_remove = keys_to_remove)
        paper_text = open(f"static/papers/{hash}/paper_docling.txt", "r").read()
        metadata = extract(
            paper_text, model_name, backend = backend, schema = schema.schema, version = "3.0", log = False 
        )
        # print("Raw metadata:", metadata)
        try:
            metadata = read_json(metadata)
        except:
            metadata = schema.generate_metadata(method = 'default')
        # print("Metadata:", metadata)
        gold_metadata = get_metadata_human(paper_link=link, schema_name = schema_name)
        scores = schema.evaluate(metadata, gold_metadata)
        # print(scores)
        results.append(scores)
    
    plt.bar(ablations, [score['f1'] for score in results])
    # plt.plot(ablations, [score['adj_recall'] for score in results])
    plt.show()

def remove_random_keys(schema, num_keys = 0):
    keys = list(schema.keys())
    keys_to_remove = random.sample(keys, num_keys)
    return keys_to_remove

def ablate_removed_keys(model_name, backend="transformers", link = "https://arxiv.org/pdf/2406.01574"):
    hash = create_hash(link)
    schema_name = "en"
    results = []
    schema_json = json.load(open(f"schema/{schema_name}.json"))
    ablations = [0, 5, 10, 15, 20, 25]
    for ablation in ablations:
        keys_to_remove = remove_random_keys(schema_json, num_keys = ablation)
        schema = Schema(schema_name = schema_name, keys_to_remove = keys_to_remove)
        paper_text = open(f"static/papers/{hash}/paper_docling.txt", "r").read()
        metadata = extract(
            paper_text, model_name, backend = backend, schema = schema.schema, version = "3.0", log = False 
        )
        # print("Raw metadata:", metadata)
        try:
            metadata = read_json(metadata)
        except:
            metadata = schema.generate_metadata(method = 'default')
        # print("Metadata:", metadata)
        gold_metadata = get_metadata_human(paper_link=link, schema_name = schema_name)
        scores = schema.evaluate(metadata, gold_metadata)
        # print(scores)
        results.append(scores)
    
    plt.bar(ablations, [score['f1'] for score in results])
    # plt.plot(ablations, [score['adj_recall'] for score in results])
    plt.show()

def ablate_tokens(model_name, backend="transformers", link = "https://arxiv.org/pdf/1806.03822", schema_name = "en"):
    hash = create_hash(link)
    schema = Schema(schema_name = schema_name)
    results = []
    lens = [256, 512, 1024, 2048, 4096]
    for len in lens:
        paper_text = open(f"static/papers/{hash}/paper_docling.txt", "r").read()
        # paper_text = open('sample_from_gemini_reversed.txt').read()
        paper_text = truncate_by_tokens(paper_text, num_tokens = len)
        metadata = extract(
            paper_text, model_name, backend = backend, schema_name = schema_name, version = "3.0", log = False 
        )
        # print("Raw metadata:", metadata)
        try:
            metadata = read_json(metadata)
        except:
            metadata = schema.generate_metadata(method = 'default')
        # print("Metadata:", metadata)
        gold_metadata = get_metadata_human(paper_link=link, schema_name = schema_name)
        scores = schema.evaluate(metadata, gold_metadata)
        results.append(scores)
    
    plt.plot(lens, [score['f1'] for score in results])
    # plt.plot(lens, [score['adj_recall'] for score in results])
    # plt.show()
model_name = "Qwen2.5-1.5B-Instruct-gemini-2.5-flash-lite-sft-merged-r_8_alpha_16-evaluated_gemini_only_slot_reversed3_cx_6144_truncated_text_schema_end_10000-1000"
# model_name = "Qwen2.5-1.5B-Instruct"
# model_name = "MeXtract-1.5B"
# example3(model_name, backend="transformers")
# ablate_tokens(model_name, backend = "transformers", schema_name = "jp")
# ablate_removed_keys(model_name, backend="transformers")
# example3("Qwen2.5-1.5B-Instruct", backend="transformers")
# example3("google/gemini-2.5-flash-lite", backend="openrouter")

### issues
### 1. the host is always the first
### 2. for none values it always predicts the first one
### 3. for tasks it predicts all of them
### 4. the authors with weird characters cause issues 
### 5. seems the issue stems from the synth data finetuning

from glob import glob
import random
random.seed(42)
files = []
for schema_name in ["ar", "en", "jp", "fr", "ru"]:
    files += glob(f"evals/{schema_name}/test/**.json")

files = random.sample(files, 25)
for file in files:
    data = json.load(open(file))
    schema_name = file.split("/")[1]
    link = data["Paper_Link"]
    print(schema_name, link)
    ablate_tokens(model_name, backend = "transformers", schema_name = schema_name, link = link)
plt.show()

